export const schedule = [
	{ time: '08:00', available: true },
	{ time: '08:30', available: true },
	{ time: '09:00', available: true },
	{ time: '09:30', available: true },
	{ time: '10:00', available: true },
	{ time: '10:30', available: true },
	{ time: '11:00', available: true },
	{ time: '11:30', available: true },
	{ time: '12:00', available: false },
	{ time: '12:30', available: false },
	{ time: '13:00', available: false },
	{ time: '13:30', available: false },
	{ time: '14:00', available: true },
	{ time: '14:30', available: true },
	{ time: '15:00', available: true },
	{ time: '15:30', available: true },
	{ time: '16:00', available: true },
	{ time: '16:30', available: true },
	{ time: '17:00', available: true },
	{ time: '17:30', available: true },
	{ time: '18:00', available: false },
	{ time: '18:30', available: false },
	{ time: '19:00', available: false },
	{ time: '19:30', available: false },
];

export const daysWeek = [
	{ day: 'Segunda', available: true },
	{ day: 'Terça', available: true },
	{ day: 'Quarta', available: true },
	{ day: 'Quinta', available: true },
	{ day: 'Sexta', available: true },
	{ day: 'Sábado', available: false },
];
